### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by kainthcool** [Just-A-Visitor/sugar-rush#2]
Hello, 
Can you invite me to the codeforces contests. My handle is: kainthcool
PS: I am not from your college, but it will help me in my preparation as well. 
Kudos for this initiative.

**Comment by Just-A-Visitor** [comment]
Sure, you can select 3 companies from this [list](https://just-a-visitor.github.io/sugar-rush/) and I'll invite you to those contests.

Also, just curious, how did you come to know about this?

**Comment by kainthcool** [comment]
Thanks, I got them.
A friend of mine shared a doc, which had a few links about the interview experiences/ questions, puzzles, etc. I got to know about this from there.
