### ISSUE TITLE
how to participate

### ISSUE THREAD

**Issue by lakshyavijh** [Just-A-Visitor/sugar-rush#3]

**Comment by Just-A-Visitor** [comment]
You can share your CF handle, and I'll add you to the first 3 contests for now. Let me know once you are done with them.

**Comment by lakshyavijh** [comment]
lakshyavijh <https://codeforces.com/profile/lakshyavijh>

Lakshya Vijh

Placement Coordinator

Department of Computer Science and Engineering

National Institute of Technology, Agartala

Contact: +91-8542882524

[image: LinkedIn] <https://www.linkedin.com/in/lakshya-vijh-382190158>

**Comment by Just-A-Visitor** [comment]
Done. Chcek your DMs on CF.

**Comment by lakshyavijh** [comment]
Got it bro thanks

Lakshya Vijh

Placement Coordinator

Department of Computer Science and Engineering

National Institute of Technology, Agartala

Contact: +91-8542882524

[image: LinkedIn] <https://www.linkedin.com/in/lakshya-vijh-382190158>
